import type { ScriptLanguage } from '@/lib/types'

export const SCRIPT_LANGUAGES: { code: ScriptLanguage; name: string; flag: string }[] = [
  { code: 'ru', name: 'Русский',            flag: '🇷🇺' },
  { code: 'en', name: 'English',            flag: '🇬🇧' },
  { code: 'es', name: 'Español',            flag: '🇪🇸' },
  { code: 'fr', name: 'Français',           flag: '🇫🇷' },
  { code: 'de', name: 'Deutsch',            flag: '🇩🇪' },
  { code: 'it', name: 'Italiano',           flag: '🇮🇹' },
  { code: 'pt', name: 'Português',          flag: '🇵🇹' },
  { code: 'zh', name: '中文',               flag: '🇨🇳' },
  { code: 'ja', name: '日本語',             flag: '🇯🇵' },
  { code: 'ko', name: '한국어',             flag: '🇰🇷' },
  { code: 'ar', name: 'العربية',            flag: '🇸🇦' },
  { code: 'hi', name: 'हिंदी',             flag: '🇮🇳' },
  { code: 'nl', name: 'Nederlands',         flag: '🇳🇱' },
  { code: 'pl', name: 'Polski',             flag: '🇵🇱' },
  { code: 'tr', name: 'Türkçe',             flag: '🇹🇷' },
  { code: 'sv', name: 'Svenska',            flag: '🇸🇪' },
  { code: 'no', name: 'Norsk',              flag: '🇳🇴' },
  { code: 'da', name: 'Dansk',              flag: '🇩🇰' },
  { code: 'fi', name: 'Suomi',              flag: '🇫🇮' },
  { code: 'uk', name: 'Українська',         flag: '🇺🇦' },
  { code: 'cs', name: 'Čeština',            flag: '🇨🇿' },
  { code: 'ro', name: 'Română',             flag: '🇷🇴' },
  { code: 'hu', name: 'Magyar',             flag: '🇭🇺' },
  { code: 'el', name: 'Ελληνικά',           flag: '🇬🇷' },
  { code: 'he', name: 'עברית',              flag: '🇮🇱' },
  { code: 'th', name: 'ภาษาไทย',           flag: '🇹🇭' },
  { code: 'id', name: 'Bahasa Indonesia',   flag: '🇮🇩' },
  { code: 'vi', name: 'Tiếng Việt',         flag: '🇻🇳' },
]
