-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- ─────────────────────────────────────────
-- Tables
-- ─────────────────────────────────────────

create table if not exists public.profiles (
  id              uuid references auth.users(id) on delete cascade primary key,
  email           text        not null,
  full_name       text,
  avatar_url      text,
  plan            text        not null default 'free'
                    check (plan in ('free', 'starter', 'pro', 'agency')),
  credits         integer     not null default 20,
  paddle_customer_id      text unique,
  paddle_subscription_id  text unique,
  onboarding_completed    boolean     not null default false,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

-- Migration: add onboarding_completed to existing databases
alter table public.profiles add column if not exists onboarding_completed boolean not null default false;

-- Migration: admin flag
alter table public.profiles add column if not exists is_admin boolean not null default false;

-- Migration: Paddle billing (add if missing — safe to run multiple times)
alter table public.profiles add column if not exists paddle_customer_id text unique;
alter table public.profiles add column if not exists paddle_subscription_id text unique;

-- Migration: referral program
alter table public.profiles add column if not exists referral_code text unique;
alter table public.profiles add column if not exists referred_by text;
alter table public.profiles add column if not exists referral_count integer not null default 0;
alter table public.profiles add column if not exists referral_credits_earned integer not null default 0;

create table if not exists public.projects (
  id              uuid        default uuid_generate_v4() primary key,
  user_id         uuid        references public.profiles(id) on delete cascade not null,
  title           text        not null default 'Новый проект',
  status          text        not null default 'draft'
                    check (status in (
                      'draft', 'generating_script', 'generating_audio',
                      'generating_subtitles', 'generating_images',
                      'generating_video', 'generating_seo', 'completed', 'failed'
                    )),
  topic           text        not null,
  duration_minutes integer    not null default 5,
  voice_id        text,
  script          text,
  audio_url       text,
  subtitle_blocks jsonb,
  scene_images    jsonb,
  image_interval  integer     not null default 10,
  thumbnail_url   text,
  video_url       text,
  seo             jsonb,
  credits_spent   integer     not null default 0,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

create table if not exists public.credit_transactions (
  id          uuid        default uuid_generate_v4() primary key,
  user_id     uuid        references public.profiles(id) on delete cascade not null,
  amount      integer     not null,
  operation   text        not null,
  project_id  uuid        references public.projects(id) on delete set null,
  created_at  timestamptz not null default now()
);

-- ─────────────────────────────────────────
-- Indexes
-- ─────────────────────────────────────────

create index if not exists projects_user_id_idx          on public.projects(user_id);
create index if not exists projects_status_idx           on public.projects(status);
create index if not exists credit_transactions_user_id_idx on public.credit_transactions(user_id);

-- ─────────────────────────────────────────
-- Auto-update updated_at
-- ─────────────────────────────────────────

create or replace function public.handle_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create trigger on_profiles_updated
  before update on public.profiles
  for each row execute function public.handle_updated_at();

create trigger on_projects_updated
  before update on public.projects
  for each row execute function public.handle_updated_at();

-- ─────────────────────────────────────────
-- Auto-create profile on signup
-- ─────────────────────────────────────────

create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email, full_name, avatar_url, credits, plan)
  values (
    new.id,
    new.email,
    new.raw_user_meta_data->>'full_name',
    new.raw_user_meta_data->>'avatar_url',
    20,
    'free'
  );
  -- referral_code is generated by the set_referral_code BEFORE INSERT trigger on profiles
  return new;
end;
$$ language plpgsql security definer;

create or replace trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ─────────────────────────────────────────
-- Credit functions (atomic, bypass RLS)
-- ─────────────────────────────────────────

create or replace function public.deduct_credits(
  p_user_id   uuid,
  p_amount    integer,
  p_operation text,
  p_project_id uuid default null
)
returns json as $$
declare
  v_credits integer;
begin
  select credits into v_credits
  from public.profiles
  where id = p_user_id
  for update;

  if v_credits < p_amount then
    return json_build_object('success', false, 'remaining', v_credits);
  end if;

  update public.profiles
  set credits = credits - p_amount
  where id = p_user_id;

  insert into public.credit_transactions (user_id, amount, operation, project_id)
  values (p_user_id, -p_amount, p_operation, p_project_id);

  return json_build_object('success', true, 'remaining', v_credits - p_amount);
end;
$$ language plpgsql security definer;

create or replace function public.add_credits(
  p_user_id    uuid,
  p_amount     integer,
  p_operation  text,
  p_project_id uuid default null
)
returns void as $$
begin
  update public.profiles
  set credits = credits + p_amount
  where id = p_user_id;

  insert into public.credit_transactions (user_id, amount, operation, project_id)
  values (p_user_id, p_amount, p_operation, p_project_id);
end;
$$ language plpgsql security definer;

-- ─────────────────────────────────────────
-- Role grants (required for RLS to work)
-- ─────────────────────────────────────────

grant usage on schema public to anon, authenticated;

grant select, update                          on public.profiles             to authenticated;
grant select, insert, update, delete          on public.projects             to authenticated;
grant select                                  on public.credit_transactions  to authenticated;

-- ─────────────────────────────────────────
-- Row Level Security
-- ─────────────────────────────────────────

alter table public.profiles             enable row level security;
alter table public.projects             enable row level security;
alter table public.credit_transactions  enable row level security;

-- Profiles
create policy "profiles: own read"
  on public.profiles for select
  using (auth.uid() = id);

create policy "profiles: own update"
  on public.profiles for update
  using (auth.uid() = id);

-- Projects
create policy "projects: own select"
  on public.projects for select
  using (auth.uid() = user_id);

create policy "projects: own insert"
  on public.projects for insert
  with check (auth.uid() = user_id);

create policy "projects: own update"
  on public.projects for update
  using (auth.uid() = user_id);

create policy "projects: own delete"
  on public.projects for delete
  using (auth.uid() = user_id);

-- Credit transactions
create policy "transactions: own select"
  on public.credit_transactions for select
  using (auth.uid() = user_id);

-- ─────────────────────────────────────────
-- Referral code auto-generation trigger
-- ─────────────────────────────────────────

create or replace function public.set_referral_code()
returns trigger as $$
begin
  if new.referral_code is null then
    new.referral_code := upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 8));
  end if;
  return new;
end;
$$ language plpgsql;

create or replace trigger set_referral_code_trigger
  before insert on public.profiles
  for each row execute function public.set_referral_code();

-- ─────────────────────────────────────────
-- Analytics events
-- ─────────────────────────────────────────

create table if not exists public.analytics_events (
  id          uuid        default uuid_generate_v4() primary key,
  user_id     uuid        references public.profiles(id) on delete cascade not null,
  event       text        not null,
  properties  jsonb       not null default '{}',
  created_at  timestamptz not null default now()
);

create index if not exists analytics_events_user_id_idx on public.analytics_events(user_id);
create index if not exists analytics_events_event_idx   on public.analytics_events(event);
create index if not exists analytics_events_created_at_idx on public.analytics_events(created_at);

alter table public.analytics_events enable row level security;

grant select on public.analytics_events to authenticated;

create policy "analytics_events: own select"
  on public.analytics_events for select
  using (auth.uid() = user_id);

-- ─────────────────────────────────────────
-- YouTube Analytics cache (24h TTL)
-- ─────────────────────────────────────────

create table if not exists public.analytics_cache (
  id          uuid        default uuid_generate_v4() primary key,
  cache_type  text        not null,
  cache_key   text        not null,
  result      jsonb       not null,
  created_at  timestamptz not null default now()
);

create unique index if not exists analytics_cache_type_key_idx
  on public.analytics_cache(cache_type, cache_key);

create index if not exists analytics_cache_created_at_idx
  on public.analytics_cache(created_at);

-- service role reads/writes cache; no RLS needed (server-side only)
alter table public.analytics_cache enable row level security;

-- ─────────────────────────────────────────
-- Storage buckets
-- ─────────────────────────────────────────

insert into storage.buckets (id, name, public)
values ('audio', 'audio', false)
on conflict do nothing;

insert into storage.buckets (id, name, public)
values ('images', 'images', true)
on conflict do nothing;

insert into storage.buckets (id, name, public)
values ('videos', 'videos', true)
on conflict do nothing;

-- Storage RLS: users can only access their own files
create policy "audio: own access"
  on storage.objects for all
  using (bucket_id = 'audio' and auth.uid()::text = (storage.foldername(name))[1]);

create policy "images: public read"
  on storage.objects for select
  using (bucket_id = 'images');

create policy "images: own write"
  on storage.objects for insert
  with check (bucket_id = 'images' and auth.uid()::text = (storage.foldername(name))[1]);

create policy "videos: public read"
  on storage.objects for select
  using (bucket_id = 'videos');

create policy "videos: service write"
  on storage.objects for insert
  with check (bucket_id = 'videos');
