-- ============================================================
-- Migration 009: Fix signup wallet initialization
-- Run ONCE in Supabase SQL Editor.
-- ============================================================
--
-- Root cause: handle_new_user trigger inserted credits=10000 but left
-- plan_credits=0, purchased_credits=0 (two-wallet columns added by migration 001).
-- deduct_credits checks plan_credits+purchased_credits, not the credits column,
-- so ALL new users registered after migration 001 could never have credits deducted.
--
-- This migration:
--   1. Repairs existing broken profiles (purchased_credits = credits - plan_credits)
--   2. Fixes handle_new_user trigger to set purchased_credits on signup
-- ============================================================

-- ─── 1. Repair existing broken profiles ──────────────────────────────────────
-- Invariant that must hold: plan_credits + purchased_credits = credits
-- Violated for: every user registered AFTER migration 001.
-- Fix: put the missing amount into purchased_credits (eternal wallet).
-- Safe to re-run: WHERE clause skips already-correct rows.

update public.profiles
set purchased_credits = credits - plan_credits
where plan_credits + purchased_credits < credits
  and credits > 0;

-- ─── 2. Fix handle_new_user trigger ──────────────────────────────────────────
-- Add purchased_credits = 10000 to the initial INSERT so new signups
-- are correctly initialized from the start.
--
-- NOTE: This replaces the function body with the placeholder secret.
-- If you have a real NUW_WEBHOOK_SECRET configured in the current DB function,
-- replace '<NUW_WEBHOOK_SECRET>' below with the actual secret before running.

create or replace function public.handle_new_user()
returns trigger as $$
declare
  _secret text := '<NUW_WEBHOOK_SECRET>';
begin
  insert into public.profiles (id, email, full_name, avatar_url, credits, plan, purchased_credits)
  values (
    new.id,
    new.email,
    new.raw_user_meta_data->>'full_name',
    new.raw_user_meta_data->>'avatar_url',
    10000,
    'free',
    10000  -- signup bonus → eternal wallet (no cap, no expiry)
  );
  -- referral_code is generated by the set_referral_code BEFORE INSERT trigger on profiles

  -- Async new-user webhook via pg_net (non-blocking; registration never blocked on failure)
  begin
    if _secret <> '' and _secret <> '<NUW_WEBHOOK_SECRET>' then
      perform net.http_post(
        url     := 'https://lefiro.co/api/webhooks/new-user',
        headers := jsonb_build_object(
          'Content-Type', 'application/json',
          'Authorization', 'Bearer ' || _secret
        ),
        body    := jsonb_build_object(
          'id',        new.id::text,
          'email',     new.email,
          'provider',  new.raw_app_meta_data->>'provider',
          'full_name', new.raw_user_meta_data->>'full_name'
        )::text
      );
    end if;
  exception when others then
    null; -- pg_net not available or call failed; registration is unaffected
  end;

  return new;
end;
$$ language plpgsql security definer;
