-- ============================================================
-- Migration 018: Signup bonus → 1 000 credits, 30-day expiry
-- ============================================================
-- Changes:
--   1. handle_new_user: 1 000 plan_credits (not purchased_credits),
--      plan_expires_at = now() + 30 days.
--   2. expire_plan: extended to burn free-user starter bonus that
--      has passed its 30-day window.
--
-- Safe for existing users: UPDATE has WHERE plan_credits + purchased_credits < credits
-- is NOT in this migration — balances of current users are untouched.
--
-- Note: _secret placeholder must be replaced with the live
-- NUW_WEBHOOK_SECRET before running (same as migrations 009 / 011).
-- ============================================================

-- ─── 1. Fix handle_new_user ────────────────────────────────────────────────
create or replace function public.handle_new_user()
returns trigger as $$
declare
  _secret text := '<NUW_WEBHOOK_SECRET>';
begin
  insert into public.profiles (
    id, email, full_name, avatar_url,
    credits, plan,
    plan_credits,      -- starter bonus → expiring wallet
    purchased_credits, -- no eternal wallet on signup
    plan_expires_at    -- bonus window: 30 days from registration
  )
  values (
    new.id,
    new.email,
    new.raw_user_meta_data->>'full_name',
    new.raw_user_meta_data->>'avatar_url',
    1000,    -- credits = plan_credits (materialized sum)
    'free',
    1000,    -- signup bonus in the expiring wallet
    0,
    now() + interval '30 days'
  );
  -- referral_code is generated by the set_referral_code BEFORE INSERT trigger on profiles

  -- Async new-user webhook via pg_net (non-blocking; registration never blocked on failure)
  begin
    if _secret <> '' and _secret <> '<NUW_WEBHOOK_SECRET>' then
      perform net.http_post(
        url     := 'https://lefiro.co/api/webhooks/new-user',
        headers := jsonb_build_object(
          'Content-Type', 'application/json',
          'Authorization', 'Bearer ' || _secret
        ),
        body    := jsonb_build_object(
          'id',        new.id::text,
          'email',     new.email,
          'provider',  new.raw_app_meta_data->>'provider',
          'full_name', new.raw_user_meta_data->>'full_name'
        )::text
      );
    end if;
  exception when others then
    null;
  end;

  return new;
end;
$$ language plpgsql security definer;

-- ─── 2. Update expire_plan to handle free-user bonus expiry ───────────────
-- Previous version bailed out immediately for plan='free' users.
-- Now: if a free user has a non-null plan_expires_at in the past,
-- their starter plan_credits are burned and plan_expires_at is cleared.
create or replace function public.expire_plan(p_user_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_plan         text;
  v_plan_credits integer;
  v_purchased    integer;
  v_expires_at   timestamptz;
begin
  select plan, plan_credits, purchased_credits, plan_expires_at
  into   v_plan, v_plan_credits, v_purchased, v_expires_at
  from   public.profiles
  where  id = p_user_id
  for update;

  if not found then
    return jsonb_build_object('ok', false, 'error', 'user_not_found');
  end if;

  -- Noop: free user whose starter window hasn't started or is still valid
  if v_plan = 'free' and (v_expires_at is null or v_expires_at >= now()) then
    return jsonb_build_object('ok', true, 'noop', true, 'reason', 'already_free');
  end if;

  -- Noop: paid plan that hasn't expired yet
  if v_plan <> 'free' and (v_expires_at is null or v_expires_at >= now()) then
    return jsonb_build_object('ok', true, 'noop', true, 'reason', 'not_expired');
  end if;

  -- Log credit burn before zeroing
  if v_plan_credits > 0 then
    insert into public.credit_transactions (user_id, amount, operation, wallet)
    values (
      p_user_id,
      -v_plan_credits,
      case when v_plan = 'free' then 'starter_bonus_expired' else 'plan_expired' end,
      'plan'
    );
  end if;

  if v_plan = 'free' then
    -- Starter bonus expired: zero plan wallet, clear expiry, keep plan='free'
    update public.profiles
    set    plan_credits      = 0,
           credits           = v_purchased,
           plan_activated_at = null,
           plan_expires_at   = null   -- reset so user is a clean free user
    where  id = p_user_id;

    return jsonb_build_object(
      'ok',                true,
      'burned',            v_plan_credits,
      'remaining_credits', v_purchased,
      'reason',            'starter_bonus_expired'
    );
  else
    -- Paid plan expired: downgrade to free, keep expires_at for audit
    update public.profiles
    set    plan              = 'free',
           plan_credits      = 0,
           credits           = v_purchased,
           plan_activated_at = null
    where  id = p_user_id;

    return jsonb_build_object(
      'ok',                true,
      'burned',            v_plan_credits,
      'remaining_credits', v_purchased
    );
  end if;
end;
$$;

-- ─── 3. Verification ──────────────────────────────────────────────────────
-- Run BEFORE applying to confirm current handle_new_user body:
--   select pg_get_functiondef(oid) from pg_proc
--   where proname = 'handle_new_user' and pronamespace = 'public'::regnamespace;
--
-- After applying: register a test account and confirm:
--   select credits, plan_credits, purchased_credits, plan_expires_at
--   from profiles where email = '<test-email>';
--   -- expected: credits=1000, plan_credits=1000, purchased_credits=0,
--   --           plan_expires_at ≈ now()+30d
